### ISSUE TITLE
[Bug]: CBA settings can't be changed in mission editor

### ISSUE THREAD

**Issue by SpadesNeil** [HakonRydland/A3-HR-Garage#7]
### Describe the bug

I thought the addon was just broken until five minutes ago when I finally saw the CBA settings, but only after launching a server with the mod running.

### How to reproduce

1) Mount this addon.
2) Add the module and vehicles to a mission.
3) Load Eden.
4) Check here.
![image](https://user-images.githubusercontent.com/6484985/195172315-4407c37c-2271-4dc5-b8ac-217ca06345cf.png)
5) It's not here.
![image](https://user-images.githubusercontent.com/6484985/195172411-f6a2c924-8273-4308-b1c3-6bd8667edecb.png)
6) Launch multiplayer.
7) Configure addons.
8) THERE it is. But why is it only here? Also why is the base capacity set to _zero_???
![image](https://user-images.githubusercontent.com/6484985/195172703-fcf2da00-a2e5-4b6f-8df2-7b99e53b83a2.png)

### Version

ArmA v2.10

### Have you altered the code?

No

### Map

Takistan (CUP)

### What server?

LAN Hosted

### Mods

```html
N/A problem occurs even when running vanilla
```

### Additional context

The whole wiki and README section of this Github seems severely outdated and poorly written. I strongly encourage going back and doing a thorough step-by-step rewrite.

The mod author seems to have written it with the assumption that whoever is adding this to their mission already knows a lot of what they're doing. You assume too much of my intelligence.

**Comment by HakonRydland** [comment]
will be fixed for next release
