### ISSUE TITLE
[Bug]: The default vehicle capacity is zero. It should probably be infinite instead.

### ISSUE THREAD

**Issue by SpadesNeil** [HakonRydland/A3-HR-Garage#8]
### Is the requested change related to a problem?

Yes.

I thought the mod was _broken_ because I followed the instructions on the workshop page and it didn't work unless I change CBA settings that I can only access when already running the server.

That is not very intuitive.

### Describe the solution you'd like.

Make the default capacity infinite, or at least an extremely high number, so that players can actually use the addon out of the box. Server admins can always configure it to limit what it does later on if they so choose.

![image](https://user-images.githubusercontent.com/6484985/195175286-f2dd8046-12c0-4e98-b3fb-569b92f2747f.png)

### Alternative soloutions

If the capacity equals 0, recognize that as "There is no limit" in the code and skip the capacity check all together.

### Additional context

Also, how does capacity increase work? That isn't explained anywhere.

**Comment by SpadesNeil** [comment]
I have been told this is actually a bug.

**Comment by HakonRydland** [comment]
default capacity is 10, and could be scaled in the range of 0-50, this will be upped to 0-150 for next release.
due to technical limitations of sqf i wont allow extreme storage capacity as that could cripple performance

**Comment by SpadesNeil** [comment]
Sounds good to me! Didn't know performance could be affected if an extreme storage capacity was chosen.
